### ISSUE TITLE
Maybe put all SESSION Data into ['chessboard'] 

### ISSUE THREAD

**Issue by MichaelMrt** [MichaelMrt/ChessPHP#45]
This could save us from creating dozens of hidden inputs to transmit data. 
We could put it all into the chessboard array and only sent the data.

Have to test how it will be decoded

**Comment by MichaelMrt03** [comment]
Also the class vars like $whitesturn need to be checked. They are doubled with $whitesturn and $_SESSION['whitesturn'] which leads to confusion

**Comment by MichaelMrt** [comment]
$_SESSION data is transmitted even without hidden inputs
